apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: entity-ssl-test
  namespace: hypermine-development
spec:
  dnsNames:
  - api.entity-test.hypersign.id
  - "*.api.entity-test.hypersign.id"
  issuerRef:
    kind: Issuer
    name: letsencrypt-production
  secretName: entity-ssl-test
