apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
      name: entity-ssl
      namespace: hypermine-development
spec:
      dnsNames:
            - api.entity.hypersign.id
            - "*.api.entity.hypersign.id"
      issuerRef:
            kind: Issuer
            name: letsencrypt-production
      secretName: entity-ssl
