---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-api
  namespace: hypermine-development
spec:
  replicas: 1

  selector:
    matchLabels:
      app: entity-api
  template:
    metadata:
      labels:
        app: entity-api
    spec:
      containers:
        - name: entity-api
          image: __GOOGLE_ARTIFACT_URL__/__GOOGLE_PROJECT_ID__/__GOOGLE_ARTIFACT_REPO__/enity-api-service:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: PORT
              value: __PORT__
            - name: BASE_DB_PATH
              value: __BASE_DB_PATH__
            - name: HID_NETWORK_RPC
              value: __HID_NETWORK_RPC__
            - name: HID_NETWORK_API
              value: __HID_NETWORK_API__
            - name: HID_NETWORK_NAMESPACE
              value: __HID_NETWORK_NAMESPACE__
            - name: EDV_BASE_URL
              value: __EDV_BASE_URL__
            - name: EDV_CONFIG_DIR
              value: __EDV_CONFIG_DIR__
            - name: EDV_DID_FILE_PATH
              value: __EDV_DID_FILE_PATH__
            - name: EDV_KEY_FILE_PATH
              value: __EDV_KEY_FILE_PATH__
            - name: MNEMONIC
              value: __MNEMONIC__
            - name: JWT_SECRET
              value: __JWT_SECRET__
            - name: WHITELISTED_CORS
              value: "['https://entity.hypersign.id','https://entity.hypersign.id','https://entity-stage.hypersign.id','https://api.entity-stage.hypersign.id','https://wallet-jagrat.hypersign.id']"

          ports:
            - containerPort: __PORT__
---
apiVersion: v1
kind: Service
metadata:
  name: enity-api-service
  namespace: hypermine-development
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

spec:
  type: NodePort
  selector:
    app: enity-api
  ports:
    - port: __PORT__
      targetPort: __PORT__
      protocol: TCP
