# issuer-lets-encrypt-production.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: hypermine-development
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pratap@hypermine.in # ❗ Replace this with your email address
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudDNS:
            project: fyre-400407
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
